# Generated by Django 5.0.1 on 2024-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x_coords',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='location',
            name='y_coords',
            field=models.FloatField(default=1.0),
        ),
    ]
